services:
    HT\UserBundle\Form\UserRolesType:
        autowire: true
        autoconfigure: true
        public: true

    ht_user.user_manager:
        class: HT\UserBundle\Doctrine\UserManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '%ht_user.model.user.class%'

    ht_user.security.login_form_authenticator:
        class: HT\UserBundle\Security\LoginFormAuthenticator
        arguments:
            - '@ht_user.user_manager'
            - '@router.default'
            - '@security.csrf.token_manager'
            - '@security.user_password_encoder.generic'

    ht_user.mailer.default:
        class: HT\UserBundle\Mailer\UserMailer
        arguments:
            - '@mailer'
            - '@router.default'
            - '@translator'
            - '@parameter_bag'

    ht_user.token_generator:
        class: HT\UserBundle\Util\TokenGenerator

    HT\UserBundle\Controller\SecurityController:
        autowire: true
        public: true

    HT\UserBundle\Controller\RegistrationController:
        autowire: true
        public: true
        arguments:
            $userManager: '@ht_user.user_manager'
            $registrationForm: '%ht_user.registration_form%'

    HT\UserBundle\Controller\ProfileController:
        autowire: true
        public: true
        arguments:
            $userManager: '@ht_user.user_manager'
            $profileForm: '%ht_user.profile_form%'

    HT\UserBundle\Controller\ChangePasswordController:
        autowire: true
        public: true
        arguments:
            $userManager: '@ht_user.user_manager'
            $changePasswordForm: '%ht_user.change_password_form%'

    HT\UserBundle\Controller\ResettingController:
        autowire: true
        public: true
        arguments:
            $userManager: '@ht_user.user_manager'
            $tokenGenerator: '@ht_user.token_generator'
            $mailer: '@ht_user.mailer.default'

    HT\UserBundle\EventListener\AuthenticationListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@security.authentication.guard_handler'
            - '@ht_user.security.login_form_authenticator'
            - '@event_dispatcher'

    HT\UserBundle\EventListener\EmailConfirmationListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@ht_user.mailer.default'
            - '@ht_user.token_generator'
            - '@router.default'
            - '@session'

    HT\UserBundle\EventListener\LoginListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@ht_user.user_manager'

    HT\UserBundle\EventListener\UserPasswordUpgrader:
        arguments:
            - '@security.user_password_encoder.generic'
        tags:
            - { name: doctrine.orm.entity_listener, event: 'prePersist', lazy: true }
            - { name: doctrine.orm.entity_listener, event: 'preUpdate', lazy: true }

    HT\UserBundle\EventListener\ResettingListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@router.default'
