services:
    HT\UserBundle\:
        autowire: true
        autoconfigure: true
        resource: '../../{Form}'

    htuser.user_manager:
        class: HT\UserBundle\Doctrine\UserManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'

    htuser.security.login_form_authenticator:
        class: HT\UserBundle\Security\LoginFormAuthenticator
        arguments:
            - '@htuser.user_manager'
            - '@router.default'
            - '@security.csrf.token_manager'
            - '@security.user_password_encoder.generic'

    htuser.mailer.twig_swift:
        class: HT\UserBundle\Mailer\TwigSwiftMailer
        public: true
        arguments:
            - '@twig'
            - '@parameter_bag'
            - '@swiftmailer.mailer'

    htuser.mailer.default:
        class: HT\UserBundle\Mailer\Mailer
        arguments:
            - '@htuser.mailer.twig_swift'
            - '@router.default'

    htuser.token_generator:
        class: HT\UserBundle\Util\TokenGenerator

    HT\UserBundle\Controller\SecurityController:
        autowire: true
        public: true

    HT\UserBundle\Controller\RegistrationController:
        autowire: true
        public: true
        arguments:
            $userManager: '@htuser.user_manager'

    HT\UserBundle\Controller\ProfileController:
        autowire: true
        public: true
        arguments:
            $userManager: '@htuser.user_manager'

    HT\UserBundle\Controller\ChangePasswordController:
        autowire: true
        public: true
        arguments:
            $userManager: '@htuser.user_manager'

    HT\UserBundle\Controller\ResettingController:
        autowire: true
        public: true
        arguments:
            $userManager: '@htuser.user_manager'
            $tokenGenerator: '@htuser.token_generator'
            $mailer: '@htuser.mailer.default'

    HT\UserBundle\EventListener\AuthenticationListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@security.authentication.guard_handler'
            - '@htuser.security.login_form_authenticator'
            - '@event_dispatcher'

    HT\UserBundle\EventListener\EmailConfirmationListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@htuser.mailer.default'
            - '@htuser.token_generator'
            - '@router.default'
            - '@session'

    HT\UserBundle\EventListener\LoginListener:
        tags: [kernel.event_subscriber]
        arguments:
            - '@doctrine.orm.default_entity_manager'

    HT\UserBundle\EventListener\UserPasswordUpgrader:
        arguments:
            - '@security.user_password_encoder.generic'
        tags:
            - { name: doctrine.orm.entity_listener, event: 'prePersist', lazy: true }
            - { name: doctrine.orm.entity_listener, event: 'preUpdate', lazy: true }
