user_resetting_request:
    path: /request
    methods: [GET]
    defaults:  { _controller: App\UserBundle\Controller\ResettingController::request }
user_resetting_send_email:
    path: /send-email
    methods: [POST]
    defaults:  { _controller: App\UserBundle\Controller\ResettingController::sendEmail }
user_resetting_check_email:
    path: /check-email
    methods: [GET]
    defaults:  { _controller: App\UserBundle\Controller\ResettingController::checkEmail }
user_resetting_reset:
    path: /reset/{token}
    methods: [GET,POST]
    defaults:  { _controller: App\UserBundle\Controller\ResettingController::reset }
