login:
    path: /login
    methods: [GET,POST]
    defaults:  { _controller: HT\UserBundle\Controller\SecurityController::login }
logout:
    path: /logout
    methods: [GET]
    defaults:  { _controller: HT\UserBundle\Controller\SecurityController::logout }
